name: VincentBradley
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8024438542779535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6dee0'
    - '#7e7a6e'
    - '#a6aeb0'
    - '#0e1215'
    - '#42516e'
  brandStrength: 1
  lightness: 0.6312250529881567
  saturation: 0.5
  rhythmicContrast: 0.29101021960377693
purpose: []
